### ISSUE TITLE
Starts Text Selection in Firefox 39

### ISSUE THREAD

**Issue by JD-Robbs** [bramstein/knockout.selection#93]
Hi there,

Amazing and very useful plugin!

It looks like in Firefox it initiates a text selection, however.

It can be re-created in Firefox 39 by clicking the first item in a list, holding SHIFT and then clicking the last item. What happens is that, as expected, all items are selected; but, on top of that, all text in between is selected, too.

**Comment by papandreou** [comment]
It would hurt some use cases if knockout-selection forced `user-select: none` (et al.) on the element it is applied to, so that's currently out of scope for this binding. The selectable items could be anything, including content that would be expected to be selectable.

If that's what you want, however, it's very easy to achieve. Simply go:

```css
.mySelectableContainer {
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

Or just `mySelectableContainer { user-select: none; }` if you use autoprefixer.
